name: TCProtect
main: net.milkycraft.tcprotect.TCProtect
version: ${project.version}
authors: [ikillforeyou, overcast, Maxim Roncace, Frostalf]
description: Allows players to define fields to protect their houses.
softdepend: [Vault]
commands:
  tcprotect:
    description: "Main command for tcprotect."
    usage: "Error, read '/rp ?' for more information."
    aliases: [rp, redp, rprotect, protect]
permissions:
  tcprotect.*:
    description: "All tcprotect commands."
    children:
      tcprotect.user: true
      tcprotect.admin: true
  tcprotect.user:
    description: "Recommended User permissions."
    default: op
    children:
      tcprotect.create: true
      tcprotect.near: true
      tcprotect.own.addmember: true
      tcprotect.own.delete: true
      tcprotect.own.info: true
      tcprotect.own.addowner: true
      tcprotect.own.removemember: true
      tcprotect.own.removeowner: true
      tcprotect.own.rename: true
      tcprotect.own.limit: true
      tcprotect.own.list: true
      tcprotect.infowand: true
      tcprotect.flag.chest: true
      tcprotect.flag.lever: true
      tcprotect.flag.button: true
      tcprotect.flag.door: true
      tcprotect.flag.snowform: true
      tcprotect.flag.icemelt: true
      tcprotect.group.preferred: true
      tcprotect.lock: true
  tcprotect.flag.all:
    description: "Access to edit all flags."
    default: op
    children:
      tcprotect.flag.pvp: true
      tcprotect.flag.chest: true
      tcprotect.flag.lever: true
      tcprotect.flag.button: true
      tcprotect.flag.door: true
      tcprotect.flag.mobs: true
      tcprotect.flag.animals: true
      tcprotect.flag.crops: true
      tcprotect.flag.invincible: true
      tcprotect.flag.homes: true
      tcprotect.flag.items: true
      tcprotect.flag.potions: true
      tcprotect.flag.snowform: true
      tcprotect.flag.icemelt: true
  tcprotect.admin:
    description: "Recommended Admin permsisions."
    default: op
    children:
      tcprotect.user: true
      tcprotect.admin.delete: true
      tcprotect.admin.removeowner: true
      tcprotect.admin.addowner: true
      tcprotect.admin.addmember: true
      tcprotect.admin.removemember: true
      tcprotect.admin.info: true
      tcprotect.admin.rename: true
      tcprotect.admin.flag: true
      tcprotect.admin.define: true
      tcprotect.admin.resetflags: true
      tcprotect.admin.unlimitedregions: true
      tcprotect.bypass: true
      tcprotect.unlimited: true
      tcprotect.magicwand: true
      tcprotect.lock.admin: true
      tcprotect.purge.bypass: true
  tcprotect.admin.resetflags:
    description: "Use /rp resetflags to reset the flags of all regions."
  tcprotect.near:
    description: "Use /rp near to find nearby regions."
  tcprotect.create:
    description: "Create regions."
  tcprotect.own.addmember:
    description: "Add members to regions you're an owner of."
  tcprotect.own.addowner:
    description: "Add owners to regions you're an owner of."
  tcprotect.own.removemember:
    description: "Remove members from regions you're an owner of."
  tcprotect.own.removeowner:
    description: "Remove owners from regions you're an owner of."
  tcprotect.own.delete:
    description: "Delete regions you're an owner of."
  tcprotect.own.rename:
    description: "Rename regions you own."
  tcprotect.own.limit:
    description: "Find the area restriction limits for yourself."
  tcprotect.own.list:
    description: "Find the information about regions you own."
  tcprotect.flag.pvp:
    description: "Toggle the pvp flag."
  tcprotect.flag.chest:
    description: "Toggle the chest access flag."
  tcprotect.flag.lever:
    description: "Toggle the lever usage flag."
  tcprotect.flag.button:
    description: "Toggle the button access flag."
  tcprotect.flag.door:
    description: "Toggle the door opening flag."
  tcprotect.flag.mobs:
    description: "Toggle the mob spawning flag."
  tcprotect.flag.animals:
    description: "Toggle the animal hurting flag."
  tcprotect.flag.potions:
    description: "Toggle the potion flag."
  tcprotect.flag.invincible:
    description: "Toggle the invincible flag."
  tcprotect.flag.crops:
    description: "Toggle the crops flag."
  tcprotect.flag.items:
    description: "Toggle the items flag."
  tcprotect.flag.superprotect:
    description: "Toggle the superprotect flag."
  tcprotect.flag.snowform:
    description: "Toggle the snowform flag."
  tcprotect.flag.icemelt:
    description: "Toggle the icemelt flag."
  tcprotect.flag.homes:
    description: "Toggle the homes flag"
  tcprotect.admin.delete:
    description: "Delete any region."
  tcprotect.admin.removeowner:
    description: "Remove owners from any region."
  tcprotect.admin.addowner:
    description: "Add owners to any region."
  tcprotect.admin.addmember:
    description: "Add members to any region."
  tcprotect.admin.removemember:
    description: "Remove members to any region."
  tcprotect.admin.super:
    description: "Allows admins to modify any region with super protection."
  tcprotect.admin.info:
    description: "Get info from any region."
  tcprotect.admin.rename:
    description: "Rename any region"
  tcprotect.admin.list:
    description: "Find the information about regions other players own."
  tcprotect.admin.flag:
    description: "Toggle flags on other's regions"
  tcprotect.admin.define:
    description: "Create large regions by selecting two points."
  tcprotect.bypass:
    description: "Build, break, or PvP In any region"
  tcprotect.unlimited:
    description: "Make any number of regions."
  tcprotect.magicwand:
    description: "Allows you to use the magic wand"
  tcprotect.infowand:
    description: "Allows you to use the information wand"
  tcprotect.group.preferred:
    description: "The default TCProtect group"
    default: true
  tcprotect.group.exclusive:
    description: "The second-level TCProtect group"
  tcprotect.group.platinum:
    description: "The highest TCProtect group"
  tcprotect.admin.unlimitedregions:
    description: "Allows for creation of unlimited regions"
  tcprotect.lock:
    description: Allows for locking of chests
  tcprotect.lock.admin:
    description: Allows for opening of all locked chests
  tcprotect.purge:
    description: Allows for manual purges
  tcprotect.purge.bypass:
    description: Allows addition of regions which bypass purges